# Generated by Django 6.0.7 on 2026-07-31 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField()),
                ('fecha_publicacion', models.DateField()),
                ('paginas', models.IntegerField()),
                ('escrito_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libreria.autor')),
            ],
        ),
    ]
